### ISSUE TITLE
Using analog input on talonsrx

### ISSUE THREAD

**Issue by mendax1234** [CrossTheRoadElec/Phoenix-Examples-Languages#51]
Our team wires an encoder on the talonsrx and we want to use it. We want to use the analog input to get the voltage. However,it seems that the analog input needs a port id because it is usally wired on the roborio. But we don't wire it on the roborio. Instead, we wire it on the talonsrx directly. So how can get the value of analog input.

**Comment by cpapplefamily** [comment]
So On the SRX are you using the[Analog Breakout Board]( http://www.ctr-electronics.com/adaptors/talon-srx-analog-breakout-board.html)? We have used a 10 turn pot for absolute position many times before. It is our preferred way since at powerup no referencing is required. Your welcome to look through our 2019 elevator, arm, and hatch floor pick up code https://github.com/GraniteCityGearheads3244/2019_Jupiter

in each of these you will see, that set the FeedbackDevice to == Analog

```
 /* Configure Sensor Source for Pirmary PID */
		_talon.configSelectedFeedbackSensor(FeedbackDevice.Analog,
											Constants.kPIDLoopIdx, 
											Constants.kTimeoutMs);
```

In all of the Subsystems you will see something like: That get the raw value and in this case converts it to something usefull to us
```
private double my_getCurrentArmAngle(){
		double m_fullRange = 150;
		double m_offset = -2.3;
		double m_sensorPos = _talon.getSelectedSensorPosition(0);
    double m_angle = (m_sensorPos / 1024) * m_fullRange + m_offset;
    if(Robot.DEBUG){
		  SmartDashboard.putNumber("m_SensorPos",m_sensorPos);
      SmartDashboard.putNumber("m_angle", m_angle);
    }
		return m_angle;
	}
```

**Comment by mendax1234** [comment]
![25083b7a28b401f3fa186e1e3fb3d75](https://user-images.githubusercontent.com/62934294/129820153-ac833a73-da18-47b6-8937-c3663b96c26a.jpg)

Is this what you said?

**Comment by cpapplefamily** [comment]
> ![25083b7a28b401f3fa186e1e3fb3d75](https://user-images.githubusercontent.com/62934294/129820153-ac833a73-da18-47b6-8937-c3663b96c26a.jpg)
> 
> Is this what you said?

Nope. That is the Magnetic encoder. It can be used as a Quadrature encoder for relative position measurement or has Pulse Width Modulated output for absolute position measurement. Both are set up similar to the example above but with 

FeedbackDevice.CTRE_MagEncoder_Relative (Quadrature)

or
FeedbackDevice.PulseWidthEncodedPosition or FeedbackDevice.CTRE_MagEncoder_Absolute

What type of subsystem is this on?

**Comment by mendax1234** [comment]
It's on a swerve drive subsystem

**Comment by mendax1234** [comment]
Hello , l use the code below , but can't get the encoder's value.

```
    m_driveMotor.configFactoryDefault();
    m_turningMotor.configFactoryDefault();
    m_driveMotor.configSelectedFeedbackSensor(FeedbackDevice.IntegratedSensor);
    m_turningMotor.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder);
```

  /**
  * Returns the current velocity of the module.
  *
  * @return The current velocity of the module.
  */
  public double getVelocity() {
    return m_driveMotor.getSelectedSensorVelocity() * ModuleConstants.kDriveEncoderDistancePerPulse * 10;
    //double veloc;
    //veloc = m_driveMotor.getSensorCollection().getIntegratedSensorVelocity();
    //return veloc* ModuleConstants.kDriveEncoderDistancePerPulse * 10;
  }

  /**
  * Returns the current angle of the module.
  *
  * @return The current angle of the module in radians.
  */
  public double getTurningRadians() {
      //return m_turningMotor.getSelectedSensorPosition() * ModuleConstants.kTurningEncoderDistancePerPulse;
      double radian;
      radian = m_turningMotor.getSelectedSensorPosition();
      return radian * ModuleConstants.kTurningEncoderDistancePerPulse;
  }

**Comment by mendax1234** [comment]
Hello , how can l get the absolute position of TalonSrx through the Quadrature encoder?

**Comment by mendax1234** [comment]
Can l use two sensors on a talonsrx?  One relative and one absolute?

**Comment by JCaporuscio** [comment]
If you're referring to using the SRX Mag Encoder in your previous picture and reading both relative and absolute position, yes you can do this.  The encoder has both quadrature (relative) and pulse-width (absolute) position.

You can only use one sensor at a time for your primary on-board closed loop in the Talon SRX.

However, you can always get the raw value with a function call to use it in your program on the roboRIO.
Use the GetSensorCollection() API:
https://www.ctr-electronics.com/downloads/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1_sensor_collection.html

So for example, to get the absolute position in java you would call:
myTalon.getSensorCollection().getPulseWidthPosition();


I want to take a step back though - what are you trying to do?
If you're the same username on chief delphi, it sounds like you're trying to do swerve.

What's your level of familiarity with closed-loop control and robot programming in general?  Swerve is a lot to take on if you're new to one or both of those.  If you haven't already, I highly recommend going through our docs step-by-step first to just get familiar with Talon and what its capabilities are: 
https://docs.ctre-phoenix.com/en/stable/ch13_MC.html
That bring-up is useful for getting familiar with the config, control, and plotting capabilities of Tuner and the basic functionality of Talon which will help with general development.

Next, move on to the sensors section:
https://docs.ctre-phoenix.com/en/stable/ch14_MCSensor.html
This will get you familiar with the sensors Talon can use as well as their resolutions and how to verify that they're working as you expect.

The last one to go through is then the closed-loop section:
https://docs.ctre-phoenix.com/en/stable/ch16_ClosedLoop.html#
This is critical to understand what the closed-loop does and how to utilize the different options for closed-loop control.  I recommend using an example from our examples repository along with the walkthrough in the docs to get familiar with one of the basic closed-loop control modes (like position) before you tackle the full implementation of swerve.  Ultimately you'll need both velocity and some form of position control in order to do swerve so it's helpful to understand them separately first.

If you have questions you can ask them here, or you can e-mail our support: support@ctr-electronics.com

**Comment by mendax1234** [comment]
Thanks . If l don't have a  analog breakout onboard . Can l config the PID0 sensor with Analog and get its sensorpostion?
```
angleMotor.configSelectedFeedbackSensor(FeedbackDevice.Analog, 0, 0);
```

**Comment by mendax1234** [comment]
Hello , l want to use a closed velocity on TalonFx. l've looked the Example code of CTRE and copied it to my code. However, when l push my XboxController, the motor doesn't seem to want to stop. l have change the Ki,Kd and KF parameters of the motor to 0 . But the result is the same . That's why and what is the right way to use Velocity closed loop.

**Comment by CoryNessCTR** [comment]
> Thanks . If l don't have a analog breakout onboard . Can l config the PID0 sensor with Analog and get its sensorpostion?

I'm not entirely sure what you mean when you ask this, you might be confusing **Analog** with **Absolute**, because you've only shown a mag encoder in your image. If you are using a mag encoder and want to get the absolute reference, use `FeedbackDevice.CTRE_MagEncoder_Absolute`. **If you are using an analog sensor**, please provide more information as to how you're connecting the sensor to the SRX, while also connecting the mag encoder.

> However, when l push my XboxController, the motor doesn't seem to want to stop

What do you mean by doesn't want to stop? In velocity-closed loop control, I'd expect the motor to spin while the joystick is pushed in a direction, as it is maintaining the velocity.

>  l have change the Ki,Kd and KF parameters of the motor to 0 . But the result is the same

If you're using the [Talon FX Velocity closed loop example](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/Java%20Talon%20FX%20(Falcon%20500)/VelocityClosedLoop/src/main/java/frc/robot/Robot.java), make sure you're pressing button 1, otherwise it will remain in percent output, snippet of the code is attached. In general, if a CTRE device is not doing what you think you are telling it to do, take a [self-test snapshot](https://docs.ctre-phoenix.com/en/stable/ch08_BringUpCAN.html#self-test-snapshot) of the device while attempting to control it. This provides you with a snapshot of the state of the device, and will provide valuable debugging information, such as what control mode it is in, what its output is, its closed loop error, and other information. Make sure all the information in the snapshot aligns with what you expect. If you're still unsure what's causing the issue, respond with the snapshot and we can help you more.

https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/a9063fd8ca1a18b3730783ac5548541992b97f39/Java%20Talon%20FX%20(Falcon%20500)/VelocityClosedLoop/src/main/java/frc/robot/Robot.java#L120-L145

**Comment by mendax1234** [comment]
> I'm not entirely sure what you mean when you ask this, you might be confusing Analog with Absolute, because you've only shown a mag encoder in your image. If you are using a mag encoder and want to get the absolute reference, use FeedbackDevice.CTRE_MagEncoder_Absolute. If you are using an analog sensor, please provide more information as to how you're connecting the sensor to the SRX, while also connecting the mag encoder.

Thanks , l mean that the "Analog Breakout onboard" is a hardware which can be installed on the TalonSRX. And our encoder is shown is the earlier thread. It seems that we don't have installed it on our robot. 

Besides, l am puzzled about how the **relative** and **absolute** encoder count its value. What's the difference between these two modes (Maybe the zero position is different? ). l want to know this because the output of TalonSRX's relative encoder (Quadrature) is sometimes more than 4096 .

> What do you mean by doesn't want to stop? In velocity-closed loop control, I'd expect the motor to spin while the joystick is pushed in a direction, as it is maintaining the velocity.

l mean that when l push the axis, the motor keeps driving and it never stops. l guess that there is something wrong with my P,I,D and kF parameters . After studying the CTRE doc, the kF parameter can either be calculated manually or by frc-characterization . However , in the CTRE's example code , 
```
kF = 1023.0/20660.0;
```

If l am also using TalonFX, can l use it directly?

**Comment by mendax1234** [comment]
Hello , l want  to tune talonfx and talonsrx's internal PID parameters  , how can l do this?

**Comment by JCaporuscio** [comment]
See the documentation here on closed-loop features and how to use them:
https://docs.ctre-phoenix.com/en/stable/ch16_ClosedLoop.html

The PID gains themselves are config parameters, see here for how to set configs:
https://docs.ctre-phoenix.com/en/stable/ch13_MC.html#configuration

**Comment by mendax1234** [comment]
Thanks , l recently have some trouble in tuning internal PID parameters on my swerve . How can l do this ? l think that it is so difficult if l use the traditional method to tune it.
