### ISSUE TITLE
Questions about arbitraryfeedforward

### ISSUE THREAD

**Issue by mendax1234** [CrossTheRoadElec/Phoenix-Examples-Languages#60]
l have looked WPILib's introduction about combining feedforward and PID. It seems that the units of feedforward calculation and PID calculation should be the same.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/62934294/166403516-b6c5fbed-dfe9-45d5-872f-7e8d70143364.png">

But when l use CTRE's `motor.set(ControlMode.Velocity, velocity, DemandType.ArbitraryFeedForward, feedforward.calculate(velocity_mps))` The unit isn't the same since the unit of `feedforward.calculate(velocity_mps)` is percentouput. But the velocity unit is falcon unit. This is confusing. Does it have the same function of the WPILib example?

So does kF and velocity closed loop has the same function with simplefeedforward(using as arbitraryfeedforward) and velocity closed loop?

**Comment by JCaporuscio** [comment]
The units of velocity closed-loop and the *arbitrary* feed-forward are not the same.  Velocity closed-loop takes a target setpoint in sensor native units per 100ms.  The arbitrary feed-forward is a scalar between -1 and +1.

The units of `feedforward.calculate(velocity_mps)` is in units of Volts, so you need to divide by your bus voltage in order to scale it between -1 and +1.

**Comment by mendax1234** [comment]
So if l divide my feedforward with 12, l can send it to arbitrary feedforward?

**Comment by JCaporuscio** [comment]
You should divide it by the bus voltage, which may not always be 12 volts - so either by the value from talon.GetBusVoltage() or by whatever your voltage compensation saturation point is (if you're using voltage compensation).
