### ISSUE TITLE
SRX Mag Encoder Reset Issue under SIM

### ISSUE THREAD

**Issue by Crossle86** [CrossTheRoadElec/Phoenix-Examples-Languages#62]
So I have a new problem with SRX Magnetic Encoder under sim. Previously I worked with CTRE on problems with resetting the
encoder under sim and having old count values come back after some time passed after reset. This was timing issues with the
frame update period and I worked that out and resets appear to work as expected.

The resets work if they are done in the same auto/teleop session, meaning for instance, in auto, if I do multiple resets
and drives based on starting at zero to some encoder count, the auto program works as expected.

What I did not recognize until yesterday, is that the reset does not work around disabling and then reenabling the robot.

Here is the scenario:
Start an auto session where code resets encoders, then drives forward a short distance. After the auto program ends, I
disable the robot, wait a few seconds, and then reenable auto mode again to rerun the same auto program.

In my trace, I see that the first auto run ends with encoders reading 10096. Disable, then reenable. The auto program
calls for encoder reset. Resets wait 36ms on 20ms frame rate. Now I trace the encoder.getposition values around the reset.
I see before reset value of 10096 and after reset value of zero. Now as it happens, another reset gets called a bit 
later, before reset value is zero and after reset values is zero. This all makes sense.

Next the code starts running the drive forward loop. I trace the encoder.getposition calls and the calls into my sim
code that set the simcollection values to set encoder count driven by the sim position change. The code runs and the robot
position does not change for a while (due to several factors but this is expected). Eventually robot sim position will change
and drive the encoder sim position. Now before any movement happens (meaning a robot position value of zero is being posted to 
encoder sim and encoder.getposition has been returning zero), about 75ms after the second reset, encoder.getposition returns 
-10096! This kills the drive forward loop as this exceeds the target encoder count and the auto program ends with no movement. 
So the encoder count from the previous auto session comes back and is negated. 

Interestingly enough, if I disable and reenable again, it all works fine and auto program completes. If I disable and reenable
again, it fails as described above.

This is all quite repeatable. I am sure this is related to how our code is structured but I can't come up with an explanation
for this behavior.

I am providing an annotated trace from our code. Look for >>
[srx_reset.txt](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/files/8633462/srx_reset.txt)

**Comment by CoryNessCTR** [comment]
> So the encoder count from the previous auto session comes back and is negated.

It looks like this is similar to the original issue you mentioned in https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/issues/56. When I check the log, this change stands out to me
`<15>12:10:24:601 robot: subsystems.DriveBase.periodic(DriveBase.java:267): cld=0.000  crd=0.000  px=1.200 py=0.500 prot=0.0 tangle=0.0 simhdg=-0.0 yaw=0.0`
to
`<15>12:10:24:605 robot: subsystems.DriveBase.periodic(DriveBase.java:267): cld=-1.219  crd=-1.219  px=-0.019 py=0.500 prot=0.0 tangle=0.0 simhdg=-0.0 yaw=0.0`

This indicates that the x position of the pose jumped, which could explain the getPosition returning -10096 since the simulation class produced a discontinuous signal back to the original position, effectively writing a position equal in magnitude but opposite in sign to the movement that just occurred.

I don't really understand why the pose is jumping like that, but based on that behavior it looks like everything is working as expected in Phoenix still.

> Interestingly enough, if I disable and reenable again, it all works fine and auto program completes. If I disable and reenable
again, it fails as described above.

I suspect that's because after you disable and reenable, the pose hasn't jumped, then it'll perform the autonomous and "wind up" the pose, so that on next disable and reenable it jumps again, causing the failure again.

**Comment by Crossle86** [comment]
So in the trace, the values cld, clr, px and py, are all calculated from the enoder position. So the encoder drives the pose that drives the robot icon on the simulated field. The encoder is driven by the values from DifferentialDriveTrainSim (DDTS) object for distance traveled based on voltages applied to talons. So when the cld, clr, pose jump backward it is because the encoder returned the negative value of the last drive forward. Note that the encoder value changes to the bad value, but the values from DDTS object being sent to encoder setQuadratureRawPosition have not yet moved from zero.

Whatever is going wrong happens between .602 and .605 in the trace. DDTS manipulation of the encoders happens prior to .602 and we see the encoders returning zero after that. At .605 with no intervening manipulation of the encoders, we see cld change from zero to -1.219, which is calculated from encoder counts. So best I can tell, the bad return from the encoders is not caused by a bad input to them.

One other observation, the time  between the last encoder reset and the bad value appearing is ~75ms. In my testing this time is pretty consistent.

Based on your reply, I have gone over the code again and I am pretty sure the code is not driving the bad encoder value, but other way round.

When  I look at the next attempt to rerun the auto program, the trace looks identical except that the incorrect encoder values do not pop up and eventually the DDTS starts driving the encoders  correctly.

Since the setQuadratureRawPosition works by integrating the values so posted with the encoders current position (as I understand it), if we are setting value of zero with setQuadratureRawPosition and the encoder suddenly "remembered" the previous 10096 value, would the integration of position zero cause the sign change? 

Hopefully this not some hard to see bug in our code. I appreciate your time looking at this.

**Comment by CoryNessCTR** [comment]
Yep, I missed that the pose is updated by encoder values when I did my review, that particular point doesn't look to be the issue, but I still think there's something you're missing from your robot code.

I'm going to step through the points I think may be related to this, and provide a diagram that explains the relationship between simulation position and sensor position, which should explain how the encoder is "remembering" the old value.
 1. <15>12:10:24:435: Encoder starts at 10096 and set *selectedSensorPosition* set to 0
 2. <15>12:10:24:477: Encoder's *selectedSensorPosition* sees the 0 value, but the *simulation raw value* still sees the old 10096 value. Any number of resets after this will only affect the *selectedSensorPosition* value, since it does not touch the *simulation raw value*
 3. <15>12:10:24:586: First call to simulationPeriodic, which will update the *simulation raw value* to the driveSim.getLeftPositionMeters(), which is near 0
 4. <15>12:10:24:602: Last time see lget=0, this is 16ms after the first call to simulationPeriodic, which is within the 20ms update period of Status 2, so it's reasonable to believe API has not yet received the updated frame.
 5. <15>12:10:24:607: CANcoder's status frame finally updates API, and we see the effect of changing the *simulation raw value* 10096 units, causing CANcoder to jump 10096 units in the opposite direction.

And the diagram that I think explains what's happening
![Untitled Diagram-Page-2 drawio](https://user-images.githubusercontent.com/28712271/168149833-6fac88f9-7eac-493b-a65d-fae6da734ac8.png)

Let me know if you want any further explanation on any of this.

**Comment by Crossle86** [comment]
Wow. Thanks for the detail. So is it a case of the 10096 being the last sim value set, then I set sensor position to zero and follow that up a bit later with setting sim position to zero, the encoder integrates the existing sim pos of 10096 with new sim pos of zero with sensor pos of zero resulting in -10096? This happening when the frame updates?

When you say "we see the effect of changing the simulation raw value 10096 units", you mean by setting the sim raw value  to zero?

So is this a matter of incorrectly resetting under sim? This is a full reset, not a reset, move, reset, move series of events during the running of a program, but starting over without rebooting the code. That is a different reset. What I am looking for is a way to set both positions to zero to start over. This may be outside what the sim api was designed to do.

Side note, you mention CANCoder in the last reply, but this on SRX encoder if that makes any difference.

**Comment by Crossle86** [comment]
If you will indulge me a bit further, a couple documentation questions:

On CANCoder getPosition dioc says:
Gets the position of the sensor. **This may be relative or absolute depending on configuration**. The units are determined by the coefficient and unit-string configuration params, default is degrees.

Does the bold sentence mean the initial value after boot or ongoing? I assume only the initial value.

Second question: For SRX Magnetic Encoder, what is the effect of:
talon.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Absolute)
as opposed to _Relative?

**Comment by CoryNessCTR** [comment]
> encoder integrates the existing sim pos of 10096 with new sim pos of zero with sensor pos of zero resulting in -10096? This happening when the frame updates?

Yes, the sensor position is held a constant number of units away from simulation position, with that constant only changing when you use the setSensorPosition API. If you setSensorPosition to 0 while the simulation position is 10096, the constant becomes -10096, so setting simulation position to 0 keeps that relationship, causing sensor position to become -10096.

> When you say "we see the effect of changing the simulation raw value 10096 units", you mean by setting the sim raw value to zero?

Yes, because the simulation raw value was 10096 and is now 0, a change of 10096 units.

> So is this a matter of incorrectly resetting under sim? 

In a way. If you insist on setting the raw position back to 0, you will have to do it first before calling setSensorPosition. The intention of the simulation value, however, is that it's always continuous and is "real". So in a real robot, after you run your motion and re-set it, the wheels will still have "seen" the distance they've traveled during operation, even if you're back at the start. If there's way to emulate that in the WPI simulation pose (reset pose on the field without affecting wheel position outputs), that would very closely mimic reality and match our API.

> Side note, you mention CANCoder in the last reply, but this on SRX encoder if that makes any difference

Yep, I corrected it. In fact if it was CANCoder, its sensor status frame is 10ms instead of 20ms, so my earlier statement about the 16ms-old frame not seeing the new position would be confusing.

> Does the bold sentence mean the initial value after boot or ongoing? I assume only the initial value.

Your assumption is correct, it's controlled by the [config sensor initialization strategy](https://api.ctr-electronics.com/phoenix/release/java/com/ctre/phoenix/sensors/CANCoder.html#configSensorInitializationStrategy(com.ctre.phoenix.sensors.SensorInitializationStrategy)), which will initialize CANCoder either to 0 or to its absolute position.

> For SRX Magnetic Encoder, what is the effect of: talon.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Absolute) as opposed to _Relative?

On a mag encoder there are two signals, the quadrature signal for relative motion and the PWM signal for absolute position. If you configure the mag encoder for absolute position using the PWM signal, the SRX's sensor position will match the absolute position as reported in the PWM signal, and for relative it will match the decoded quadrature signal. The downside of PWM's absolute is that it's an ~4ms rise-rise time, so your sensor updates slower than the 1ms closed-loop period, and its maximum rotational velocity is 6600 RPM compared to quadrature's 15000 RPM.

In simulation, the difference is in what sim collection api you use, either setQuadrature or setPulseWidth. In theory, you could even set both, with there being a real offset between the two so you can use the pulse width signal to seed the position of the quadrature (using setSensorPosition) and closed-loop on the quadrature for the faster update rates, something many teams do with SRXs and mag encoders to make use of the absolute position while working around its limitations.

**Comment by Crossle86** [comment]
It all makes sense now. I took your suggestion about to restart the simulated position tracking and it appears to give the effect I am looking for. All seems good at this point.

Thanks for all the help.
